export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_ITINERARIES = "FETCH_ITINERARIES";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const POST_COMMENT = "POST_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
